#port 수정
server:
  port: 9090
  servlet:
    session:
      tracking-modes: cookie



#DB Connection
spring:
  datasource:
    url: 1
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: dh1
   
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        
  thymeleaf:
    cache: false
 
logging.level:
  org:
    hibernate:
      SQL: debug
      type: debug  
    
    
#Kakao
kakao:
  clientId: 1
  redirectUri: h1
  restApiKey: 7f1
  
#myUrl
my:
  loginUrl : loc1
  aiurl : 1