#port 수정
server:
  port: 9090
  servlet:
    session:
      tracking-modes: cookie



#DB Connection
spring:
  datasource:
    url: ${url}
    driver-class-name: ${driverClassName}
    username: ${username}
    password: ${password}
   
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        
  thymeleaf:
    cache: false
 
logging.level:
  org:
    hibernate:
      SQL: debug
      type: debug  
    
    
#Kakao
kakao:
  clientId: ${clientId}
  redirectUri: ${redirectUri}
  restApiKey: ${restApiKey}


  
#myUrl
my:
  loginUrl : ${loginUrl}
  aiurl : ${aiurl}
