#port 수정
server:
  port: 9090
  servlet:
    session:
      tracking-modes: cookie



#DB Connection
spring:
  datasource:
    url: jdbc:mariadb://svc.sel5.cloudtype.app:30496
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: dhsmfdjEo123!
   
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        
  thymeleaf:
    cache: false
 
logging.level:
  org:
    hibernate:
      SQL: debug
      type: debug  
    
    
#Kakao
kakao:
  clientId: 7fdfd8565afe58703c42be53fa7c4047
  redirectUri: http://localhost:9090/member/kakao
  restApiKey: 7fdfd8565afe58703c42be53fa7c4047
  
#myUrl
my:
  loginUrl : localhost:3000/